### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by BruceLuke** [lizzyhku/OASD#2]
您的论文写的非常棒，实验也做得很好，但对于这个数据我有一些疑问，这个pickle文件里是包含了成都和西安两个城市的数据么？里面的数据的含义是什么呢？谢谢

**Comment by lizzyhku** [comment]
您好，是的，包含两个城市的数据，包含的数据经过map matching处理以后得到的road segments。
感谢您对我们工作的关注，您有任何问题可以继续联系我。

**Comment by BruceLuke** [comment]
感谢您的回复，请问您可以分享滴滴在西安和成都的原始数据集吗，目前滴滴官网中，有关相关内容的网页无法访问。
再次感谢！

**Comment by lizzyhku** [comment]
您好，这份原始数据我也没有，我只有处理过的map matching数据。
很抱歉。
感谢您感兴趣我们的论文， 如果您还有问题，再联系我。

**Comment by BruceLuke** [comment]
谢谢您的回复，请问如何评估西安的数据在这个模型上的效果呢，我注意到在data_utils里
G = nx.read_adjlist(traj_path+"chengdu.adjlist", create_using=nx.DiGraph, nodetype=int)
data_dict_chengdu = pickle.load(open(traj_path+'data_dict_chengdu.pkl', 'rb'), encoding='bytes')
这两行代码是用于切换评估成都或西安吗？

**Comment by lizzyhku** [comment]
是的。

**Comment by BruceLuke** [comment]
那请问xian.adjlist是需要自己生成吗？

**Comment by lizzyhku** [comment]
是的
________________________________
发件人: Bruce Luke ***@***.***>
发送时间: 2023年6月2日 11:05
收件人: lizzyhku/OASD ***@***.***>
抄送: ***@***.*** ***@***.***>; State change ***@***.***>
主题: Re: [lizzyhku/OASD] 您好 (Issue #2)


那请问xian.adjlist是需要自己生成吗？

―

**Comment by zhaozhihua97** [comment]
看到您前面提到，您是使用了匹配后的结果，请问您的数据是来自Toast那篇论文吗？

**Comment by lizzyhku** [comment]
是的
________________________________
发件人: zhz ***@***.***>
发送时间: 2024年8月3日 18:01
收件人: lizzyhku/OASD ***@***.***>
抄送: ***@***.*** ***@***.***>; State change ***@***.***>
主题: Re: [lizzyhku/OASD] 您好 (Issue #2)


This is an external email.

看到您前面提到，您是使用了匹配后的结果，请问您的数据是来自Toast那篇论文吗？

―

**Comment by zhaozhihua97** [comment]
我没有找到Toast的代码库，请问您是通过开源代码得到的，还是通过作者得到的？相关的资料方便提供一下吗。万分感谢！

**Comment by lizzyhku** [comment]
我们组前年和他们组合作，所以是通过作者得到的。
去年年初开始就没有合作了。
________________________________
发件人: zhz ***@***.***>
发送时间: 2024年8月3日 18:06
收件人: lizzyhku/OASD ***@***.***>
抄送: ***@***.*** ***@***.***>; State change ***@***.***>
主题: Re: [lizzyhku/OASD] 您好 (Issue #2)


This is an external email.

我没有找到Toast的代码库，请问您是通过开源代码得到的，还是通过作者得到的？相关的资料方便提供一下吗。万分感谢！

―
