### ISSUE TITLE
您好，我还有一个问题是，您的baseline DEEPTEA是如何复现的，因为我并没有找到这篇文章的代码

### ISSUE THREAD

**Issue by BruceLuke** [lizzyhku/OASD#3]

**Comment by lizzyhku** [comment]
您好，没有找到代码的事自己复现的。

**Comment by BruceLuke** [comment]
好的，感谢！

**Comment by lizzyhku** [comment]
不客气，感谢您感兴趣我们的论文。有问题还可以继续联系我们。

**Comment by BruceLuke** [comment]
如果可以的话，您可以分享deeptea的代码吗，感谢！
lu.fangbo@foxmail.com

**Comment by lizzyhku** [comment]
Hi Bruce,
我们的baseline里面没有deeptea。
我们论文的实验表格里面有我们用的所有的baselines。
感谢你对我们的工作感兴趣，有其他的问题可以继续联系我们。


________________________________
发件人: Bruce Luke ***@***.***>
发送时间: 2023年6月6日 14:47
收件人: lizzyhku/OASD ***@***.***>
抄送: ***@***.*** ***@***.***>; State change ***@***.***>
主题: Re: [lizzyhku/OASD] 您好，我还有一个问题是，您的baseline DEEPTEA是如何复现的，因为我并没有找到这篇文章的代码 (Issue #3)


如果可以的话，您可以分享deeptea的代码吗，感谢！
***@***.******@***.***>

―

**Comment by BruceLuke** [comment]
感谢您的回复，非常抱歉我看错了内容，谢谢
